version: "3.9"

# networks:
#     web:
#       driver:  bridge


services:
  search:
    build: 
      context: ./docker
      network: host
    # networks:
    #   - web
    # network_mode: "host"
    ports:
      - "5001:5000"
    volumes:
      - $DATA_DIR:/home/data/local/
      - .:/home/
    image: "search_img"
    depends_on:
      - chrome
    tty: true
    environment:
      - TZ=Europe/Budapest 



  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    # network_mode: "host"
    # networks:
    #   - web
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
    environment:
    # not tested properly
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - TZ=Europe/Budapest 
  
#   docker-compose up \
# --abort-on-container-exit \
# --exit-code-from search