version: "3.9"

# networks:
#     web:
#       driver:  bridge

services:
  search: #docker-compose run -d --name szb_relief relief
    build: ./docker
    # networks:
    #   - web
    ports:
      - "5001:5000"
    volumes:
      - $DATA_DIR:/home/data/local/
      - .:/home/
    image: "search_img"
    depends_on:
      - chrome
    tty: true

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    # networks:
    #   - web
    ports:
      - "4445:4445"
    privileged: true
    shm_size: 2g
  
#   docker-compose up \
# --abort-on-container-exit \
# --exit-code-from search